//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp6
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities2 : DbContext
    {
        public Entities2()
            : base("name=Entities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Авторизация> Авторизация { get; set; }
        public virtual DbSet<Вид_дома> Вид_дома { get; set; }
        public virtual DbSet<Договор_на_оказание_услуг> Договор_на_оказание_услуг { get; set; }
        public virtual DbSet<Запрос> Запрос { get; set; }
        public virtual DbSet<Клиент> Клиент { get; set; }
        public virtual DbSet<Недвижимость> Недвижимость { get; set; }
        public virtual DbSet<Оплата> Оплата { get; set; }
        public virtual DbSet<Район> Район { get; set; }
        public virtual DbSet<Риелтор> Риелтор { get; set; }
        public virtual DbSet<Справочник_помещения> Справочник_помещения { get; set; }
        public virtual DbSet<Статус_оплаты> Статус_оплаты { get; set; }
        public virtual DbSet<Счёт> Счёт { get; set; }
    }
}
