//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Договор_на_оказание_услуг
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Договор_на_оказание_услуг()
        {
            this.Клиент = new HashSet<Клиент>();
        }
    
        public int ID_договора { get; set; }
        public Nullable<System.DateTime> Дата { get; set; }
        public Nullable<int> Код_риелтора { get; set; }
        public Nullable<int> Код_недвижимости { get; set; }
        public Nullable<int> Код_клиента { get; set; }
        public Nullable<int> Сумма { get; set; }
    
        public virtual Риелтор Риелтор { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Клиент> Клиент { get; set; }
    }
}
