//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Запрос
    {
        public int ID_запроса { get; set; }
        public Nullable<int> Площадь_помещения { get; set; }
        public string Тип { get; set; }
        public string Бюджет { get; set; }
        public Nullable<int> ID_клиента { get; set; }
    
        public virtual Клиент Клиент { get; set; }
    }
}
