//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Недвижимость
    {
        public int ID_недвижимости { get; set; }
        public string Стоимость { get; set; }
        public Nullable<int> ID_статуса { get; set; }
        public Nullable<int> ID_района { get; set; }
        public string Адрес { get; set; }
        public Nullable<int> ID_вида { get; set; }
        public string количество_комнат { get; set; }
        public string метраж { get; set; }
        public int ID_риелтора { get; set; }
    
        public virtual Вид_дома Вид_дома { get; set; }
        public virtual Район Район { get; set; }
        public virtual Риелтор Риелтор { get; set; }
        public virtual Статус_оплаты Статус_оплаты { get; set; }
    }
}
